/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as StatusRouteImport } from './routes/status'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WalkthroughRouteImport } from './routes/walkthrough'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAuditorRouteImport } from './routes/_authenticated.auditor'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated.compliance'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated.credits'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated.discover'
import { Route as AuthenticatedFacilitationRouteImport } from './routes/_authenticated.facilitation'
import { Route as AuthenticatedFunderRouteImport } from './routes/_authenticated.funder'
import { Route as AuthenticatedGuidedRouteImport } from './routes/_authenticated.guided'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedRegistryRouteImport } from './routes/_authenticated.registry'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated.support'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated.trades'
import { Route as AuthenticatedWorkflowRouteImport } from './routes/_authenticated.workflow'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsWebhooksRouteImport } from './routes/docs.webhooks'
import { Route as ProductsAuditLedgerRouteImport } from './routes/products.audit-ledger'
import { Route as ProductsComplianceEngineRouteImport } from './routes/products.compliance-engine'
import { Route as ProductsTradeDeskRouteImport } from './routes/products.trade-desk'
import { Route as SolutionsFinanceRouteImport } from './routes/solutions.finance'
import { Route as SolutionsSovereignsRouteImport } from './routes/solutions.sovereigns'
import { Route as SolutionsTradersRouteImport } from './routes/solutions.traders'
import { Route as AuthenticatedAccountBillingRouteImport } from './routes/_authenticated.account.billing'
import { Route as AuthenticatedAccountSettingsRouteImport } from './routes/_authenticated.account.settings'
import { Route as AuthenticatedDealIdRouteImport } from './routes/_authenticated.deal.$id'
import { Route as AuthenticatedDeveloperDocsRouteImport } from './routes/_authenticated.developer.docs'
import { Route as AuthenticatedDeveloperKeysRouteImport } from './routes/_authenticated.developer.keys'
import { Route as AuthenticatedDeveloperNotificationsRouteImport } from './routes/_authenticated.developer.notifications'
import { Route as AuthenticatedDeveloperSchemaRouteImport } from './routes/_authenticated.developer.schema'
import { Route as AuthenticatedDeveloperSupportRouteImport } from './routes/_authenticated.developer.support'
import { Route as AuthenticatedDeveloperUsageRouteImport } from './routes/_authenticated.developer.usage'
import { Route as AuthenticatedDeveloperWebhooksRouteImport } from './routes/_authenticated.developer.webhooks'
import { Route as AuthenticatedGovernanceAuditsRouteImport } from './routes/_authenticated.governance.audits'
import { Route as AuthenticatedGovernanceEntitiesRouteImport } from './routes/_authenticated.governance.entities'
import { Route as AuthenticatedGovernanceHealthRouteImport } from './routes/_authenticated.governance.health'
import { Route as AuthenticatedGovernanceNotificationsRouteImport } from './routes/_authenticated.governance.notifications'
import { Route as AuthenticatedGovernanceTriageRouteImport } from './routes/_authenticated.governance.triage'
import { Route as AuthenticatedTransactionsNewRouteImport } from './routes/_authenticated.transactions.new'
import { Route as AuthenticatedTxIdStageStepRouteImport } from './routes/_authenticated.tx.$id.$stage.$step'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WalkthroughRoute = WalkthroughRouteImport.update({
  id: '/walkthrough',
  path: '/walkthrough',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditorRoute = AuthenticatedAuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFacilitationRoute =
  AuthenticatedFacilitationRouteImport.update({
    id: '/facilitation',
    path: '/facilitation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFunderRoute = AuthenticatedFunderRouteImport.update({
  id: '/funder',
  path: '/funder',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuidedRoute = AuthenticatedGuidedRouteImport.update({
  id: '/guided',
  path: '/guided',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRegistryRoute = AuthenticatedRegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowRoute = AuthenticatedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsWebhooksRoute = DocsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DocsRoute,
} as any)
const ProductsAuditLedgerRoute = ProductsAuditLedgerRouteImport.update({
  id: '/products/audit-ledger',
  path: '/products/audit-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsComplianceEngineRoute =
  ProductsComplianceEngineRouteImport.update({
    id: '/products/compliance-engine',
    path: '/products/compliance-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsTradeDeskRoute = ProductsTradeDeskRouteImport.update({
  id: '/products/trade-desk',
  path: '/products/trade-desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsFinanceRoute = SolutionsFinanceRouteImport.update({
  id: '/solutions/finance',
  path: '/solutions/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSovereignsRoute = SolutionsSovereignsRouteImport.update({
  id: '/solutions/sovereigns',
  path: '/solutions/sovereigns',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsTradersRoute = SolutionsTradersRouteImport.update({
  id: '/solutions/traders',
  path: '/solutions/traders',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountBillingRoute =
  AuthenticatedAccountBillingRouteImport.update({
    id: '/account/billing',
    path: '/account/billing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountSettingsRoute =
  AuthenticatedAccountSettingsRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDealIdRoute = AuthenticatedDealIdRouteImport.update({
  id: '/deal/$id',
  path: '/deal/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDeveloperDocsRoute =
  AuthenticatedDeveloperDocsRouteImport.update({
    id: '/developer/docs',
    path: '/developer/docs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperKeysRoute =
  AuthenticatedDeveloperKeysRouteImport.update({
    id: '/developer/keys',
    path: '/developer/keys',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperNotificationsRoute =
  AuthenticatedDeveloperNotificationsRouteImport.update({
    id: '/developer/notifications',
    path: '/developer/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperSchemaRoute =
  AuthenticatedDeveloperSchemaRouteImport.update({
    id: '/developer/schema',
    path: '/developer/schema',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperSupportRoute =
  AuthenticatedDeveloperSupportRouteImport.update({
    id: '/developer/support',
    path: '/developer/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperUsageRoute =
  AuthenticatedDeveloperUsageRouteImport.update({
    id: '/developer/usage',
    path: '/developer/usage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDeveloperWebhooksRoute =
  AuthenticatedDeveloperWebhooksRouteImport.update({
    id: '/developer/webhooks',
    path: '/developer/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceAuditsRoute =
  AuthenticatedGovernanceAuditsRouteImport.update({
    id: '/governance/audits',
    path: '/governance/audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceEntitiesRoute =
  AuthenticatedGovernanceEntitiesRouteImport.update({
    id: '/governance/entities',
    path: '/governance/entities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceHealthRoute =
  AuthenticatedGovernanceHealthRouteImport.update({
    id: '/governance/health',
    path: '/governance/health',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceNotificationsRoute =
  AuthenticatedGovernanceNotificationsRouteImport.update({
    id: '/governance/notifications',
    path: '/governance/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGovernanceTriageRoute =
  AuthenticatedGovernanceTriageRouteImport.update({
    id: '/governance/triage',
    path: '/governance/triage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionsNewRoute =
  AuthenticatedTransactionsNewRouteImport.update({
    id: '/transactions/new',
    path: '/transactions/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTxIdStageStepRoute =
  AuthenticatedTxIdStageStepRouteImport.update({
    id: '/tx/$id/$stage/$step',
    path: '/tx/$id/$stage/$step',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/walkthrough': typeof WalkthroughRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditor': typeof AuthenticatedAuditorRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/facilitation': typeof AuthenticatedFacilitationRoute
  '/funder': typeof AuthenticatedFunderRoute
  '/guided': typeof AuthenticatedGuidedRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/deal/$id': typeof AuthenticatedDealIdRoute
  '/developer/docs': typeof AuthenticatedDeveloperDocsRoute
  '/developer/keys': typeof AuthenticatedDeveloperKeysRoute
  '/developer/notifications': typeof AuthenticatedDeveloperNotificationsRoute
  '/developer/schema': typeof AuthenticatedDeveloperSchemaRoute
  '/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/developer/usage': typeof AuthenticatedDeveloperUsageRoute
  '/developer/webhooks': typeof AuthenticatedDeveloperWebhooksRoute
  '/governance/audits': typeof AuthenticatedGovernanceAuditsRoute
  '/governance/entities': typeof AuthenticatedGovernanceEntitiesRoute
  '/governance/health': typeof AuthenticatedGovernanceHealthRoute
  '/governance/notifications': typeof AuthenticatedGovernanceNotificationsRoute
  '/governance/triage': typeof AuthenticatedGovernanceTriageRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/tx/$id/$stage/$step': typeof AuthenticatedTxIdStageStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/walkthrough': typeof WalkthroughRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/auditor': typeof AuthenticatedAuditorRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/facilitation': typeof AuthenticatedFacilitationRoute
  '/funder': typeof AuthenticatedFunderRoute
  '/guided': typeof AuthenticatedGuidedRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/registry': typeof AuthenticatedRegistryRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/workflow': typeof AuthenticatedWorkflowRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/account/billing': typeof AuthenticatedAccountBillingRoute
  '/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/deal/$id': typeof AuthenticatedDealIdRoute
  '/developer/docs': typeof AuthenticatedDeveloperDocsRoute
  '/developer/keys': typeof AuthenticatedDeveloperKeysRoute
  '/developer/notifications': typeof AuthenticatedDeveloperNotificationsRoute
  '/developer/schema': typeof AuthenticatedDeveloperSchemaRoute
  '/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/developer/usage': typeof AuthenticatedDeveloperUsageRoute
  '/developer/webhooks': typeof AuthenticatedDeveloperWebhooksRoute
  '/governance/audits': typeof AuthenticatedGovernanceAuditsRoute
  '/governance/entities': typeof AuthenticatedGovernanceEntitiesRoute
  '/governance/health': typeof AuthenticatedGovernanceHealthRoute
  '/governance/notifications': typeof AuthenticatedGovernanceNotificationsRoute
  '/governance/triage': typeof AuthenticatedGovernanceTriageRoute
  '/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/tx/$id/$stage/$step': typeof AuthenticatedTxIdStageStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/status': typeof StatusRoute
  '/verify-email': typeof VerifyEmailRoute
  '/walkthrough': typeof WalkthroughRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/auditor': typeof AuthenticatedAuditorRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/facilitation': typeof AuthenticatedFacilitationRoute
  '/_authenticated/funder': typeof AuthenticatedFunderRoute
  '/_authenticated/guided': typeof AuthenticatedGuidedRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/registry': typeof AuthenticatedRegistryRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/webhooks': typeof DocsWebhooksRoute
  '/products/audit-ledger': typeof ProductsAuditLedgerRoute
  '/products/compliance-engine': typeof ProductsComplianceEngineRoute
  '/products/trade-desk': typeof ProductsTradeDeskRoute
  '/solutions/finance': typeof SolutionsFinanceRoute
  '/solutions/sovereigns': typeof SolutionsSovereignsRoute
  '/solutions/traders': typeof SolutionsTradersRoute
  '/_authenticated/account/billing': typeof AuthenticatedAccountBillingRoute
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRoute
  '/_authenticated/deal/$id': typeof AuthenticatedDealIdRoute
  '/_authenticated/developer/docs': typeof AuthenticatedDeveloperDocsRoute
  '/_authenticated/developer/keys': typeof AuthenticatedDeveloperKeysRoute
  '/_authenticated/developer/notifications': typeof AuthenticatedDeveloperNotificationsRoute
  '/_authenticated/developer/schema': typeof AuthenticatedDeveloperSchemaRoute
  '/_authenticated/developer/support': typeof AuthenticatedDeveloperSupportRoute
  '/_authenticated/developer/usage': typeof AuthenticatedDeveloperUsageRoute
  '/_authenticated/developer/webhooks': typeof AuthenticatedDeveloperWebhooksRoute
  '/_authenticated/governance/audits': typeof AuthenticatedGovernanceAuditsRoute
  '/_authenticated/governance/entities': typeof AuthenticatedGovernanceEntitiesRoute
  '/_authenticated/governance/health': typeof AuthenticatedGovernanceHealthRoute
  '/_authenticated/governance/notifications': typeof AuthenticatedGovernanceNotificationsRoute
  '/_authenticated/governance/triage': typeof AuthenticatedGovernanceTriageRoute
  '/_authenticated/transactions/new': typeof AuthenticatedTransactionsNewRoute
  '/_authenticated/tx/$id/$stage/$step': typeof AuthenticatedTxIdStageStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/glossary'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/verify-email'
    | '/walkthrough'
    | '/admin'
    | '/auditor'
    | '/compliance'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/facilitation'
    | '/funder'
    | '/guided'
    | '/inbox'
    | '/registry'
    | '/support'
    | '/trades'
    | '/workflow'
    | '/docs/api'
    | '/docs/webhooks'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/account/billing'
    | '/account/settings'
    | '/deal/$id'
    | '/developer/docs'
    | '/developer/keys'
    | '/developer/notifications'
    | '/developer/schema'
    | '/developer/support'
    | '/developer/usage'
    | '/developer/webhooks'
    | '/governance/audits'
    | '/governance/entities'
    | '/governance/health'
    | '/governance/notifications'
    | '/governance/triage'
    | '/transactions/new'
    | '/tx/$id/$stage/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/glossary'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/verify-email'
    | '/walkthrough'
    | '/admin'
    | '/auditor'
    | '/compliance'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/facilitation'
    | '/funder'
    | '/guided'
    | '/inbox'
    | '/registry'
    | '/support'
    | '/trades'
    | '/workflow'
    | '/docs/api'
    | '/docs/webhooks'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/account/billing'
    | '/account/settings'
    | '/deal/$id'
    | '/developer/docs'
    | '/developer/keys'
    | '/developer/notifications'
    | '/developer/schema'
    | '/developer/support'
    | '/developer/usage'
    | '/developer/webhooks'
    | '/governance/audits'
    | '/governance/entities'
    | '/governance/health'
    | '/governance/notifications'
    | '/governance/triage'
    | '/transactions/new'
    | '/tx/$id/$stage/$step'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/docs'
    | '/forgot-password'
    | '/glossary'
    | '/pricing'
    | '/reset-password'
    | '/status'
    | '/verify-email'
    | '/walkthrough'
    | '/_authenticated/admin'
    | '/_authenticated/auditor'
    | '/_authenticated/compliance'
    | '/_authenticated/credits'
    | '/_authenticated/dashboard'
    | '/_authenticated/discover'
    | '/_authenticated/facilitation'
    | '/_authenticated/funder'
    | '/_authenticated/guided'
    | '/_authenticated/inbox'
    | '/_authenticated/registry'
    | '/_authenticated/support'
    | '/_authenticated/trades'
    | '/_authenticated/workflow'
    | '/docs/api'
    | '/docs/webhooks'
    | '/products/audit-ledger'
    | '/products/compliance-engine'
    | '/products/trade-desk'
    | '/solutions/finance'
    | '/solutions/sovereigns'
    | '/solutions/traders'
    | '/_authenticated/account/billing'
    | '/_authenticated/account/settings'
    | '/_authenticated/deal/$id'
    | '/_authenticated/developer/docs'
    | '/_authenticated/developer/keys'
    | '/_authenticated/developer/notifications'
    | '/_authenticated/developer/schema'
    | '/_authenticated/developer/support'
    | '/_authenticated/developer/usage'
    | '/_authenticated/developer/webhooks'
    | '/_authenticated/governance/audits'
    | '/_authenticated/governance/entities'
    | '/_authenticated/governance/health'
    | '/_authenticated/governance/notifications'
    | '/_authenticated/governance/triage'
    | '/_authenticated/transactions/new'
    | '/_authenticated/tx/$id/$stage/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GlossaryRoute: typeof GlossaryRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  StatusRoute: typeof StatusRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WalkthroughRoute: typeof WalkthroughRoute
  ProductsAuditLedgerRoute: typeof ProductsAuditLedgerRoute
  ProductsComplianceEngineRoute: typeof ProductsComplianceEngineRoute
  ProductsTradeDeskRoute: typeof ProductsTradeDeskRoute
  SolutionsFinanceRoute: typeof SolutionsFinanceRoute
  SolutionsSovereignsRoute: typeof SolutionsSovereignsRoute
  SolutionsTradersRoute: typeof SolutionsTradersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walkthrough': {
      id: '/walkthrough'
      path: '/walkthrough'
      fullPath: '/walkthrough'
      preLoaderRoute: typeof WalkthroughRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditor': {
      id: '/_authenticated/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuthenticatedAuditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/facilitation': {
      id: '/_authenticated/facilitation'
      path: '/facilitation'
      fullPath: '/facilitation'
      preLoaderRoute: typeof AuthenticatedFacilitationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/funder': {
      id: '/_authenticated/funder'
      path: '/funder'
      fullPath: '/funder'
      preLoaderRoute: typeof AuthenticatedFunderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guided': {
      id: '/_authenticated/guided'
      path: '/guided'
      fullPath: '/guided'
      preLoaderRoute: typeof AuthenticatedGuidedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/registry': {
      id: '/_authenticated/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof AuthenticatedRegistryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/webhooks': {
      id: '/docs/webhooks'
      path: '/webhooks'
      fullPath: '/docs/webhooks'
      preLoaderRoute: typeof DocsWebhooksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/products/audit-ledger': {
      id: '/products/audit-ledger'
      path: '/products/audit-ledger'
      fullPath: '/products/audit-ledger'
      preLoaderRoute: typeof ProductsAuditLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/compliance-engine': {
      id: '/products/compliance-engine'
      path: '/products/compliance-engine'
      fullPath: '/products/compliance-engine'
      preLoaderRoute: typeof ProductsComplianceEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/trade-desk': {
      id: '/products/trade-desk'
      path: '/products/trade-desk'
      fullPath: '/products/trade-desk'
      preLoaderRoute: typeof ProductsTradeDeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/finance': {
      id: '/solutions/finance'
      path: '/solutions/finance'
      fullPath: '/solutions/finance'
      preLoaderRoute: typeof SolutionsFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/sovereigns': {
      id: '/solutions/sovereigns'
      path: '/solutions/sovereigns'
      fullPath: '/solutions/sovereigns'
      preLoaderRoute: typeof SolutionsSovereignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/traders': {
      id: '/solutions/traders'
      path: '/solutions/traders'
      fullPath: '/solutions/traders'
      preLoaderRoute: typeof SolutionsTradersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/billing': {
      id: '/_authenticated/account/billing'
      path: '/account/billing'
      fullPath: '/account/billing'
      preLoaderRoute: typeof AuthenticatedAccountBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deal/$id': {
      id: '/_authenticated/deal/$id'
      path: '/deal/$id'
      fullPath: '/deal/$id'
      preLoaderRoute: typeof AuthenticatedDealIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/docs': {
      id: '/_authenticated/developer/docs'
      path: '/developer/docs'
      fullPath: '/developer/docs'
      preLoaderRoute: typeof AuthenticatedDeveloperDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/keys': {
      id: '/_authenticated/developer/keys'
      path: '/developer/keys'
      fullPath: '/developer/keys'
      preLoaderRoute: typeof AuthenticatedDeveloperKeysRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/notifications': {
      id: '/_authenticated/developer/notifications'
      path: '/developer/notifications'
      fullPath: '/developer/notifications'
      preLoaderRoute: typeof AuthenticatedDeveloperNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/schema': {
      id: '/_authenticated/developer/schema'
      path: '/developer/schema'
      fullPath: '/developer/schema'
      preLoaderRoute: typeof AuthenticatedDeveloperSchemaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/support': {
      id: '/_authenticated/developer/support'
      path: '/developer/support'
      fullPath: '/developer/support'
      preLoaderRoute: typeof AuthenticatedDeveloperSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/usage': {
      id: '/_authenticated/developer/usage'
      path: '/developer/usage'
      fullPath: '/developer/usage'
      preLoaderRoute: typeof AuthenticatedDeveloperUsageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/developer/webhooks': {
      id: '/_authenticated/developer/webhooks'
      path: '/developer/webhooks'
      fullPath: '/developer/webhooks'
      preLoaderRoute: typeof AuthenticatedDeveloperWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance/audits': {
      id: '/_authenticated/governance/audits'
      path: '/governance/audits'
      fullPath: '/governance/audits'
      preLoaderRoute: typeof AuthenticatedGovernanceAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance/entities': {
      id: '/_authenticated/governance/entities'
      path: '/governance/entities'
      fullPath: '/governance/entities'
      preLoaderRoute: typeof AuthenticatedGovernanceEntitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance/health': {
      id: '/_authenticated/governance/health'
      path: '/governance/health'
      fullPath: '/governance/health'
      preLoaderRoute: typeof AuthenticatedGovernanceHealthRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance/notifications': {
      id: '/_authenticated/governance/notifications'
      path: '/governance/notifications'
      fullPath: '/governance/notifications'
      preLoaderRoute: typeof AuthenticatedGovernanceNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/governance/triage': {
      id: '/_authenticated/governance/triage'
      path: '/governance/triage'
      fullPath: '/governance/triage'
      preLoaderRoute: typeof AuthenticatedGovernanceTriageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions/new': {
      id: '/_authenticated/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof AuthenticatedTransactionsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tx/$id/$stage/$step': {
      id: '/_authenticated/tx/$id/$stage/$step'
      path: '/tx/$id/$stage/$step'
      fullPath: '/tx/$id/$stage/$step'
      preLoaderRoute: typeof AuthenticatedTxIdStageStepRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAuditorRoute: typeof AuthenticatedAuditorRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedFacilitationRoute: typeof AuthenticatedFacilitationRoute
  AuthenticatedFunderRoute: typeof AuthenticatedFunderRoute
  AuthenticatedGuidedRoute: typeof AuthenticatedGuidedRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedRegistryRoute: typeof AuthenticatedRegistryRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedWorkflowRoute: typeof AuthenticatedWorkflowRoute
  AuthenticatedAccountBillingRoute: typeof AuthenticatedAccountBillingRoute
  AuthenticatedAccountSettingsRoute: typeof AuthenticatedAccountSettingsRoute
  AuthenticatedDealIdRoute: typeof AuthenticatedDealIdRoute
  AuthenticatedDeveloperDocsRoute: typeof AuthenticatedDeveloperDocsRoute
  AuthenticatedDeveloperKeysRoute: typeof AuthenticatedDeveloperKeysRoute
  AuthenticatedDeveloperNotificationsRoute: typeof AuthenticatedDeveloperNotificationsRoute
  AuthenticatedDeveloperSchemaRoute: typeof AuthenticatedDeveloperSchemaRoute
  AuthenticatedDeveloperSupportRoute: typeof AuthenticatedDeveloperSupportRoute
  AuthenticatedDeveloperUsageRoute: typeof AuthenticatedDeveloperUsageRoute
  AuthenticatedDeveloperWebhooksRoute: typeof AuthenticatedDeveloperWebhooksRoute
  AuthenticatedGovernanceAuditsRoute: typeof AuthenticatedGovernanceAuditsRoute
  AuthenticatedGovernanceEntitiesRoute: typeof AuthenticatedGovernanceEntitiesRoute
  AuthenticatedGovernanceHealthRoute: typeof AuthenticatedGovernanceHealthRoute
  AuthenticatedGovernanceNotificationsRoute: typeof AuthenticatedGovernanceNotificationsRoute
  AuthenticatedGovernanceTriageRoute: typeof AuthenticatedGovernanceTriageRoute
  AuthenticatedTransactionsNewRoute: typeof AuthenticatedTransactionsNewRoute
  AuthenticatedTxIdStageStepRoute: typeof AuthenticatedTxIdStageStepRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAuditorRoute: AuthenticatedAuditorRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedFacilitationRoute: AuthenticatedFacilitationRoute,
  AuthenticatedFunderRoute: AuthenticatedFunderRoute,
  AuthenticatedGuidedRoute: AuthenticatedGuidedRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedRegistryRoute: AuthenticatedRegistryRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedWorkflowRoute: AuthenticatedWorkflowRoute,
  AuthenticatedAccountBillingRoute: AuthenticatedAccountBillingRoute,
  AuthenticatedAccountSettingsRoute: AuthenticatedAccountSettingsRoute,
  AuthenticatedDealIdRoute: AuthenticatedDealIdRoute,
  AuthenticatedDeveloperDocsRoute: AuthenticatedDeveloperDocsRoute,
  AuthenticatedDeveloperKeysRoute: AuthenticatedDeveloperKeysRoute,
  AuthenticatedDeveloperNotificationsRoute:
    AuthenticatedDeveloperNotificationsRoute,
  AuthenticatedDeveloperSchemaRoute: AuthenticatedDeveloperSchemaRoute,
  AuthenticatedDeveloperSupportRoute: AuthenticatedDeveloperSupportRoute,
  AuthenticatedDeveloperUsageRoute: AuthenticatedDeveloperUsageRoute,
  AuthenticatedDeveloperWebhooksRoute: AuthenticatedDeveloperWebhooksRoute,
  AuthenticatedGovernanceAuditsRoute: AuthenticatedGovernanceAuditsRoute,
  AuthenticatedGovernanceEntitiesRoute: AuthenticatedGovernanceEntitiesRoute,
  AuthenticatedGovernanceHealthRoute: AuthenticatedGovernanceHealthRoute,
  AuthenticatedGovernanceNotificationsRoute:
    AuthenticatedGovernanceNotificationsRoute,
  AuthenticatedGovernanceTriageRoute: AuthenticatedGovernanceTriageRoute,
  AuthenticatedTransactionsNewRoute: AuthenticatedTransactionsNewRoute,
  AuthenticatedTxIdStageStepRoute: AuthenticatedTxIdStageStepRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
  DocsWebhooksRoute: typeof DocsWebhooksRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
  DocsWebhooksRoute: DocsWebhooksRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GlossaryRoute: GlossaryRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  StatusRoute: StatusRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WalkthroughRoute: WalkthroughRoute,
  ProductsAuditLedgerRoute: ProductsAuditLedgerRoute,
  ProductsComplianceEngineRoute: ProductsComplianceEngineRoute,
  ProductsTradeDeskRoute: ProductsTradeDeskRoute,
  SolutionsFinanceRoute: SolutionsFinanceRoute,
  SolutionsSovereignsRoute: SolutionsSovereignsRoute,
  SolutionsTradersRoute: SolutionsTradersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
